---

- hosts: ROUTERS
  gather_facts: false
  connection: local

  tasks:
    - name: CHANGE HOSTNAME
      ios_config:
        lines:
          - hostname router1

    - name: CONFIGURE INTERFACE
      ios_config:
        lines:
        - description Interface configured with ansible
        - ip address 192.168.1.1 255.255.255.0
        - no shutdown
        parents: interface GigabitEthernet1 
     
      
    - name: LOADING NEW ACL INTO DEVICE
      ios_config:
        lines:
        - 10 permit ip host 192.168.0.8 any log
        - 20 permit ip host 192.168.0.30 any log
        - 30 permit ip host 192.168.0.1 any log
        - 20 permit ip host 192.168.0.150 any log
        - 20 permit ip host 192.168.0.200 any log
        parents: ip access-list extended ansible_test_acl
        before: no ip access-list extended ansible_test_acl
        match: exact

    - name: SAVE RUNNING CONFIG TO START-UP CONFIG
      ios_config:
        save_when: modified

